<!-- JS here -->
<script src="{{ asset('assets/js/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('assets/js/01-ajax-form.js') }}"></script>
<script src="{{ asset('assets/js/02-bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/03-jquery.appear.js') }}"></script>
<script src="{{ asset('assets/js/04-swiper.min.js') }}"></script>
<script src="{{ asset('assets/js/05-jquery.odometer.min.js') }}"></script>
<script src="{{ asset('assets/js/06-jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('assets/js/07-jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('assets/js/08-slick.min.js') }}"></script>
<script src="{{ asset('assets/js/09-wow.min.js') }}"></script>
<script src="{{ asset('assets/js/10-jquery.circleType.js') }}"></script>
<script src="{{ asset('assets/js/11-jquery.lettering.min.js') }}"></script>
<script src="{{ asset('assets/js/12-TweenMax.min.js') }}"></script>
<script src="{{ asset('assets/vendor/jarallax/jarallax.min.js') }}"></script>
<script src="{{ asset('assets/vendor/marquee/marquee.min.js') }}"></script>
<script src="{{ asset('assets/vendor/odometer/odometer.min.js') }}"></script>
@yield('script')
<script src="{{ asset('assets/js/main.js') }}"></script>
